name: 빌드 및 EC2 배포

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: 빌드
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: JDK 7 설정
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '7'
        cache: maven
    
    - name: Maven 설정
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: '3.6.3'
    
    - name: Maven으로 빌드
      run: |
        mvn -B clean compile test package \
          -Dmaven.compiler.source=1.7 \
          -Dmaven.compiler.target=1.7 \
          -Djava.source=1.7 \
          -Djava.target=1.7
    
    - name: 배포 패키지 압축
      run: |
        mkdir -p deployment
        cp target/tomcat-sample-app.war deployment/
        cp -r scripts deployment/
        cp appspec.yml deployment/
        cd deployment
        zip -r ../tomcat-sample-app.zip .
        
    - name: 빌드 아티팩트 업로드
      uses: actions/upload-artifact@v2
      with:
        name: deployment-package
        path: tomcat-sample-app.zip
        retention-days: 1

  deploy:
    name: 배포
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - name: 빌드 아티팩트 다운로드
      uses: actions/download-artifact@v2
      with:
        name: deployment-package
    
    - name: AWS 자격 증명 설정
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: S3에 아티팩트 업로드
      run: aws s3 cp tomcat-sample-app.zip s3://${{ secrets.S3_BUCKET }}/tomcat-sample-app.zip
    
    - name: CodeDeploy 배포 생성
      run: |
        aws deploy create-deployment \
          --application-name tomcat-app \
          --deployment-group-name tomcat-app-deployment-group \
          --s3-location bucket=${{ secrets.S3_BUCKET }},bundleType=zip,key=tomcat-sample-app.zip \
          --file-exists-behavior OVERWRITE 